export const listData = {
  mainCrousal: {
    orderId: 1,
    type: "mainCrousal",
    images: [
      "https://www.yesstyle.com/blog/wp-content/uploads/2025/03/Featured-Image_Spring-Fashion-For-Every-Persona.png",
      "https://www.yesstyle.com/blog/wp-content/uploads/2024/05/denim_featured.webp",
      "https://www.yesstyle.com/blog/wp-content/uploads/2024/03/blog-open-graph-image_inner-child_revised-1024x538.webp",
      "https://www.yesstyle.com/blog/wp-content/uploads/2025/05/MBTI-Outfits-NT_Feature-Image-1-1024x630.png",
      "https://www.yesstyle.com/blog/wp-content/uploads/2025/04/MBTI-Outfits-NT_Feature-Image-1-1-1024x630.webp",
      "https://www.yesstyle.com/blog/wp-content/uploads/2025/04/bags_featured2.webp",
      "https://www.yesstyle.com/blog/wp-content/uploads/2024/11/kpop-soloist-ft-img.webp",
      "https://www.yesstyle.com/blog/wp-content/uploads/2024/09/crazy-ft-img.webp",
      "https://www.yesstyle.com/blog/wp-content/uploads/2024/08/fashionmenufeatureimage_sandals.webp",
      "https://www.yesstyle.com/blog/wp-content/uploads/2024/05/athleisure-featured-780-x-480-px.webp",
      "https://www.yesstyle.com/blog/wp-content/uploads/2023/06/Jun19_Summer-Occasions_0.webp",
      "https://www.yesstyle.com/blog/wp-content/uploads/2023/06/Featured-image_Barbie_1.webp",
    ],
  },
  navigators: {
    orderId: 2,
    type: "navigators",
    images: [
      { name: "Cloths" },
      {
        name: "Perfuems",
      },
      { name: "Flowers" },
      { name: "MakeUp" },
      {
        name: "Haircare",
      },
      {
        name: "Skincare",
      },
      { name: "Bags" },
      { name: "Spa" },
      { name: "Glasses" },
      { name: "Rings" },
      {
        name: "Accessries",
      },
      { name: "Sandels" },
      { name: "Watches" },
      { name: "Footwear" },
    ],
  },
  dynamicImageVideoData: {
    orderId: 3,
    type: "dynamicImageVideoData",
    mainTitle: "Featured Combos",
    data: [
      {
        image:
          "https://www.yesstyle.com/blog/wp-content/uploads/2025/05/infj-1024x1024.png",
        video: null,
        brandImage: "",
        des: "Curated cute fashion bundles to complete your pastel vibe.",
        topName: "Spring Blossom Set",
        tags: [
          { text: "Pastel Core", icons: "" },
          { text: "Soft Girl Look", icons: "" },
        ],
        metaDataList: [
          {
            image:
              "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
            title: "Lace Puff Dress",
            des: "Elegant puff sleeves with floral lace detail.",
            price: "2490",
            fakePrice: "3790",
            discount: "34",
            rating: "4.8",
            ratingQuantity: "324",
          },
          {
            image:
              "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
            title: "Pearl Hairband",
            des: "Dainty pearl-studded hairband for princess looks.",
            price: "390",
            fakePrice: "699",
            discount: "44",
            rating: "4.4",
            ratingQuantity: "189",
          },
        ],
      },
      {
        image:
          "https://www.yesstyle.com/blog/wp-content/uploads/2025/04/INTJ-1-1024x1024.webp",
        video: null,
        brandImage: "",
        des: "Sweet summer sets to make every walk feel like a picnic.",
        topName: "Sunshine Picnic Combo",
        tags: [
          { text: "Boho Chic", icons: "" },
          { text: "Summer Ready", icons: "" },
        ],
        metaDataList: [
          {
            image:
              "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
            title: "Straw Bucket Hat",
            des: "Keep it shady and stylish with floral accents.",
            price: "780",
            fakePrice: "1490",
            discount: "48",
            rating: "4.2",
            ratingQuantity: "211",
          },
          {
            image:
              "https://gd.image-qoo10.jp/li/291/595/7159595291.g_300-w-st_g.jpg",
            title: "Mini Ruffle Dress",
            des: "Breathable, flirty and perfect for sunny days.",
            price: "2090",
            fakePrice: "2990",
            discount: "30",
            rating: "4.5",
            ratingQuantity: "311",
          },
        ],
      },
      {
        image:
          "https://www.yesstyle.com/blog/wp-content/uploads/2025/03/Cottagecore-Spring-1024x1024.png",
        video: null,
        brandImage: "",
        des: "Embrace the fairycore mood with dreamy textures and soft tones.",
        topName: "Fairy Garden Picks",
        tags: [
          { text: "Cottagecore", icons: "" },
          { text: "Fairy Aesthetic", icons: "" },
        ],
        metaDataList: [
          {
            image:
              "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
            title: "Tulle Midi Skirt",
            des: "Floaty and magical, perfect for spring afternoons.",
            price: "2190",
            fakePrice: "3290",
            discount: "33",
            rating: "4.6",
            ratingQuantity: "148",
          },
          {
            image:
              "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
            title: "Floral Embroidery Top",
            des: "Delicate rose-stitched top with puff sleeves.",
            price: "1290",
            fakePrice: "1990",
            discount: "35",
            rating: "4.3",
            ratingQuantity: "265",
          },
        ],
      },
      {
        image:
          "https://www.yesstyle.com/blog/wp-content/uploads/2025/03/Boho-Spring-1-1024x1024.png",
        video: null,
        brandImage: "",
        des: "Free-spirited combos for dreamy souls and wandering hearts.",
        topName: "Boho Dream Set",
        tags: [
          { text: "Wanderlust", icons: "" },
          { text: "Vintage Vibe", icons: "" },
        ],
        metaDataList: [
          {
            image:
              "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
            title: "Macrame Sling Bag",
            des: "Handwoven aesthetic with floral charm.",
            price: "890",
            fakePrice: "1590",
            discount: "44",
            rating: "4.1",
            ratingQuantity: "176",
          },
          {
            image:
              "https://gd.image-qoo10.jp/li/291/595/7159595291.g_300-w-st_g.jpg",
            title: "Crochet Shrug",
            des: "Layer it over tanks or dresses for soft indie looks.",
            price: "1990",
            fakePrice: "2890",
            discount: "31",
            rating: "4.6",
            ratingQuantity: "219",
          },
        ],
      },
      {
        image:
          "https://www.yesstyle.com/blog/wp-content/uploads/2023/09/Splay_2-1024x1024.webp",
        video: null,
        brandImage: "",
        des: "For the romantics — pink-toned pieces that say love softly.",
        topName: "Blush Babe Bundle",
        tags: [
          { text: "Romanticcore", icons: "" },
          { text: "Blush Aesthetic", icons: "" },
        ],
        metaDataList: [
          {
            image:
              "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
            title: "Ribbon Wrap Skirt",
            des: "Satin ribbon tie, perfect for dates or café hopping.",
            price: "1650",
            fakePrice: "2790",
            discount: "41",
            rating: "4.7",
            ratingQuantity: "342",
          },
          {
            image:
              "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
            title: "Heart Hoop Earrings",
            des: "Subtle yet sparkly with kawaii charm.",
            price: "520",
            fakePrice: "990",
            discount: "47",
            rating: "4.4",
            ratingQuantity: "158",
          },
        ],
      },
      {
        image:
          "https://www.yesstyle.com/blog/wp-content/uploads/2023/05/belly-conklin-2-1024x1024.webp",
        video: null,
        brandImage: "",
        des: "Chic picks for cozy days and rainy weekends.",
        topName: "Cozy Cloud Combo",
        tags: [
          { text: "Homebody Looks", icons: "" },
          { text: "Warm & Fuzzy", icons: "" },
        ],
        metaDataList: [
          {
            image:
              "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
            title: "Oversized Hoodie",
            des: "Snuggle up with marshmallow-soft fleece.",
            price: "1890",
            fakePrice: "2690",
            discount: "30",
            rating: "4.5",
            ratingQuantity: "199",
          },
          {
            image:
              "https://gd.image-qoo10.jp/li/291/595/7159595291.g_300-w-st_g.jpg",
            title: "Fuzzy Slippers",
            des: "Pink bunny-style slippers for soft landings.",
            price: "790",
            fakePrice: "1290",
            discount: "38",
            rating: "4.3",
            ratingQuantity: "120",
          },
        ],
      },
    ],
  },
  longVerticalList: {
    type: "longVerticalList",
    mainTitle: "Fashion Picks",
    data: [
      {
        title: "Top Picks for Summer",
        metaDataList: [
          {
            image: "https://example.com/images/bikini-set.jpg",
            title: "Tropical Bikini Set",
            des: "Bold prints with a flattering fit and stretch fabric.",
            price: "1499",
            fakePrice: "2599",
            discount: "42",
            rating: "4.5",
            ratingQuantity: "190",
          },
          {
            image: "https://example.com/images/beach-coverup.jpg",
            title: "Sheer Beach Cover-up",
            des: "Elegant, sheer and lightweight for poolside glam.",
            price: "1099",
            fakePrice: "1999",
            discount: "45",
            rating: "4.3",
            ratingQuantity: "120",
          },
          {
            image: "https://example.com/images/linen-shorts.jpg",
            title: "Linen Shorts",
            des: "Soft fabric with drawstring waist for comfort.",
            price: "999",
            fakePrice: "1999",
            discount: "50",
            rating: "4.5",
            ratingQuantity: "160",
          },
          {
            image: "https://example.com/images/crochet-top.jpg",
            title: "Crochet Crop Top",
            des: "Handwoven detail with a boho flair for beach parties.",
            price: "899",
            fakePrice: "1699",
            discount: "47",
            rating: "4.1",
            ratingQuantity: "134",
          },
          {
            image: "https://example.com/images/waterproof-tote.jpg",
            title: "Waterproof Beach Tote",
            des: "Spacious and stylish tote for beach essentials.",
            price: "799",
            fakePrice: "1499",
            discount: "47",
            rating: "4.4",
            ratingQuantity: "101",
          },

          {
            image: "https://example.com/images/floral-maxi.jpg",
            title: "Floral Cotton Dress",
            des: "Lightweight and breathable with elegant floral patterns.",
            price: "1299",
            fakePrice: "2999",
            discount: "57",
            rating: "4.6",
            ratingQuantity: "210",
          },
          {
            image: "https://example.com/images/linen-top.jpg",
            title: "Sleeveless Linen Top",
            des: "Cool and airy for hot summer days.",
            price: "899",
            fakePrice: "1799",
            discount: "50",
            rating: "4.2",
            ratingQuantity: "115",
          },
          {
            image: "https://example.com/images/beach-sandals.jpg",
            title: "Beach Sandals",
            des: "Water-resistant, durable flip-flops for casual wear.",
            price: "499",
            fakePrice: "899",
            discount: "44",
            rating: "4.3",
            ratingQuantity: "98",
          },
          {
            image: "https://example.com/images/sun-hat.jpg",
            title: "Straw Sun Hat",
            des: "Classic design to keep you shaded in style.",
            price: "599",
            fakePrice: "1199",
            discount: "50",
            rating: "4.0",
            ratingQuantity: "87",
          },
          {
            image: "https://example.com/images/wrap-skirt.jpg",
            title: "Swimsuit Wrap Skirt",
            des: "Chic and light cover-up for beachwear.",
            price: "899",
            fakePrice: "1599",
            discount: "43",
            rating: "4.4",
            ratingQuantity: "88",
          },
        ],
      },
      {
        title: "Beachwear Favorites",
        metaDataList: [
          {
            image: "https://example.com/images/bikini-set.jpg",
            title: "Tropical Bikini Set",
            des: "Bold prints with a flattering fit and stretch fabric.",
            price: "1499",
            fakePrice: "2599",
            discount: "42",
            rating: "4.5",
            ratingQuantity: "190",
          },
          {
            image: "https://example.com/images/beach-coverup.jpg",
            title: "Sheer Beach Cover-up",
            des: "Elegant, sheer and lightweight for poolside glam.",
            price: "1099",
            fakePrice: "1999",
            discount: "45",
            rating: "4.3",
            ratingQuantity: "120",
          },
          {
            image: "https://example.com/images/linen-shorts.jpg",
            title: "Linen Shorts",
            des: "Soft fabric with drawstring waist for comfort.",
            price: "999",
            fakePrice: "1999",
            discount: "50",
            rating: "4.5",
            ratingQuantity: "160",
          },
          {
            image: "https://example.com/images/crochet-top.jpg",
            title: "Crochet Crop Top",
            des: "Handwoven detail with a boho flair for beach parties.",
            price: "899",
            fakePrice: "1699",
            discount: "47",
            rating: "4.1",
            ratingQuantity: "134",
          },
          {
            image: "https://example.com/images/waterproof-tote.jpg",
            title: "Waterproof Beach Tote",
            des: "Spacious and stylish tote for beach essentials.",
            price: "799",
            fakePrice: "1499",
            discount: "47",
            rating: "4.4",
            ratingQuantity: "101",
          },
          {
            image: "https://example.com/images/floral-maxi.jpg",
            title: "Floral Cotton Dress",
            des: "Lightweight and breathable with elegant floral patterns.",
            price: "1299",
            fakePrice: "2999",
            discount: "57",
            rating: "4.6",
            ratingQuantity: "210",
          },
          {
            image: "https://example.com/images/linen-top.jpg",
            title: "Sleeveless Linen Top",
            des: "Cool and airy for hot summer days.",
            price: "899",
            fakePrice: "1799",
            discount: "50",
            rating: "4.2",
            ratingQuantity: "115",
          },
          {
            image: "https://example.com/images/beach-sandals.jpg",
            title: "Beach Sandals",
            des: "Water-resistant, durable flip-flops for casual wear.",
            price: "499",
            fakePrice: "899",
            discount: "44",
            rating: "4.3",
            ratingQuantity: "98",
          },
          {
            image: "https://example.com/images/sun-hat.jpg",
            title: "Straw Sun Hat",
            des: "Classic design to keep you shaded in style.",
            price: "599",
            fakePrice: "1199",
            discount: "50",
            rating: "4.0",
            ratingQuantity: "87",
          },
          {
            image: "https://example.com/images/wrap-skirt.jpg",
            title: "Swimsuit Wrap Skirt",
            des: "Chic and light cover-up for beachwear.",
            price: "899",
            fakePrice: "1599",
            discount: "43",
            rating: "4.4",
            ratingQuantity: "88",
          },
        ],
      },
      {
        title: "Casual Daywear",
        metaDataList: [
          {
            image: "https://example.com/images/floral-maxi.jpg",
            title: "Floral Cotton Dress",
            des: "Lightweight and breathable with elegant floral patterns.",
            price: "1299",
            fakePrice: "2999",
            discount: "57",
            rating: "4.6",
            ratingQuantity: "210",
          },
          {
            image: "https://example.com/images/linen-top.jpg",
            title: "Sleeveless Linen Top",
            des: "Cool and airy for hot summer days.",
            price: "899",
            fakePrice: "1799",
            discount: "50",
            rating: "4.2",
            ratingQuantity: "115",
          },
          {
            image: "https://example.com/images/beach-sandals.jpg",
            title: "Beach Sandals",
            des: "Water-resistant, durable flip-flops for casual wear.",
            price: "499",
            fakePrice: "899",
            discount: "44",
            rating: "4.3",
            ratingQuantity: "98",
          },
          {
            image: "https://example.com/images/sun-hat.jpg",
            title: "Straw Sun Hat",
            des: "Classic design to keep you shaded in style.",
            price: "599",
            fakePrice: "1199",
            discount: "50",
            rating: "4.0",
            ratingQuantity: "87",
          },
          {
            image: "https://example.com/images/wrap-skirt.jpg",
            title: "Swimsuit Wrap Skirt",
            des: "Chic and light cover-up for beachwear.",
            price: "899",
            fakePrice: "1599",
            discount: "43",
            rating: "4.4",
            ratingQuantity: "88",
          },
          {
            image: "https://example.com/images/denim-skirt.jpg",
            title: "Button-Front Denim Skirt",
            des: "Vintage-inspired skirt for everyday outings.",
            price: "1399",
            fakePrice: "2299",
            discount: "39",
            rating: "4.2",
            ratingQuantity: "144",
          },
          {
            image: "https://example.com/images/oversized-tshirt.jpg",
            title: "Oversized Graphic T-Shirt",
            des: "Comfy cotton tee with vibrant prints.",
            price: "699",
            fakePrice: "1199",
            discount: "42",
            rating: "4.6",
            ratingQuantity: "212",
          },
          {
            image: "https://example.com/images/leggings.jpg",
            title: "Stretchy High-Waist Leggings",
            des: "Perfect fit for yoga or lounging at home.",
            price: "799",
            fakePrice: "1499",
            discount: "47",
            rating: "4.7",
            ratingQuantity: "338",
          },
          {
            image: "https://example.com/images/canvas-sneakers.jpg",
            title: "Canvas Sneakers",
            des: "Light and breathable shoes for everyday comfort.",
            price: "999",
            fakePrice: "1999",
            discount: "50",
            rating: "4.3",
            ratingQuantity: "176",
          },
          {
            image: "https://example.com/images/tote-bag.jpg",
            title: "Casual Cotton Tote Bag",
            des: "Eco-friendly bag with aesthetic prints.",
            price: "449",
            fakePrice: "899",
            discount: "50",
            rating: "4.1",
            ratingQuantity: "198",
          },
        ],
      },
    ],
  },
  slidedList: {
    type: "slidedList",
    mainTitle: "Trending Women’s Fashion",
    metaData: [
      {
        image: "https://example.com/images/floral-maxi-dress.jpg",
        title: "Floral Maxi Dress",
        des: "Flowy and feminine dress perfect for summer outings.",
        price: "1799",
        fakePrice: "2999",
        discount: "40",
        rating: "4.6",
        ratingQuantity: "892",
      },
      {
        image: "https://example.com/images/boho-top.jpg",
        title: "Boho Chic Blouse",
        des: "Lightweight, embroidered top with flared sleeves.",
        price: "1299",
        fakePrice: "2399",
        discount: "46",
        rating: "4.2",
        ratingQuantity: "1342",
      },
      {
        image: "https://example.com/images/high-waist-jeans.jpg",
        title: "High-Waist Skinny Jeans",
        des: "Stretchy denim for a flattering silhouette.",
        price: "1599",
        fakePrice: "2799",
        discount: "43",
        rating: "4.0",
        ratingQuantity: "304",
      },
      {
        image: "https://example.com/images/linen-trouser.jpg",
        title: "Relaxed Linen Trousers",
        des: "Breathable fabric for all-day comfort and style.",
        price: "1399",
        fakePrice: "2399",
        discount: "42",
        rating: "4.3",
        ratingQuantity: "650",
      },
      {
        image: "https://example.com/images/makeup-pouch.jpg",
        title: "Printed Makeup Pouch",
        des: "Stylish and spacious pouch to carry your essentials.",
        price: "499",
        fakePrice: "999",
        discount: "50",
        rating: "4.5",
        ratingQuantity: "211",
      },
      {
        image: "https://example.com/images/oversized-sunglasses.jpg",
        title: "Oversized Sunglasses",
        des: "UV-protected stylish shades for a bold look.",
        price: "799",
        fakePrice: "1499",
        discount: "47",
        rating: "4.8",
        ratingQuantity: "1048",
      },
      {
        image: "https://example.com/images/crossbody-bag.jpg",
        title: "Mini Crossbody Bag",
        des: "Trendy vegan leather bag for casual outings.",
        price: "999",
        fakePrice: "1999",
        discount: "50",
        rating: "4.1",
        ratingQuantity: "712",
      },
      {
        image: "https://example.com/images/cotton-kurti.jpg",
        title: "Printed Cotton Kurti",
        des: "Comfortable daily wear with beautiful block prints.",
        price: "899",
        fakePrice: "1699",
        discount: "47",
        rating: "4.0",
        ratingQuantity: "388",
      },
      {
        image: "https://example.com/images/ankle-boots.jpg",
        title: "Ankle-Length Boots",
        des: "Perfect for layering in fall and winter.",
        price: "1999",
        fakePrice: "3299",
        discount: "39",
        rating: "4.4",
        ratingQuantity: "278",
      },
      {
        image: "https://example.com/images/hair-accessories-set.jpg",
        title: "Hair Accessories Set",
        des: "Assorted stylish clips and bands in one pack.",
        price: "349",
        fakePrice: "699",
        discount: "50",
        rating: "3.9",
        ratingQuantity: "192",
      },
      {
        image: "https://example.com/images/floral-maxi-dress.jpg",
        title: "Floral Maxi Dress",
        des: "Flowy and feminine dress perfect for summer outings.",
        price: "1799",
        fakePrice: "2999",
        discount: "40",
        rating: "4.6",
        ratingQuantity: "892",
      },
      {
        image: "https://example.com/images/boho-top.jpg",
        title: "Boho Chic Blouse",
        des: "Lightweight, embroidered top with flared sleeves.",
        price: "1299",
        fakePrice: "2399",
        discount: "46",
        rating: "4.2",
        ratingQuantity: "1342",
      },
      {
        image: "https://example.com/images/high-waist-jeans.jpg",
        title: "High-Waist Skinny Jeans",
        des: "Stretchy denim for a flattering silhouette.",
        price: "1599",
        fakePrice: "2799",
        discount: "43",
        rating: "4.0",
        ratingQuantity: "304",
      },
      {
        image: "https://example.com/images/linen-trouser.jpg",
        title: "Relaxed Linen Trousers",
        des: "Breathable fabric for all-day comfort and style.",
        price: "1399",
        fakePrice: "2399",
        discount: "42",
        rating: "4.3",
        ratingQuantity: "650",
      },
      {
        image: "https://example.com/images/makeup-pouch.jpg",
        title: "Printed Makeup Pouch",
        des: "Stylish and spacious pouch to carry your essentials.",
        price: "499",
        fakePrice: "999",
        discount: "50",
        rating: "4.5",
        ratingQuantity: "211",
      },
    ],
  },

  quadList: {
    type: "quadList",
    mainTitle: "Gisduhf",
    metaData: [
      {
        image:
          "https://gd.image-qoo10.jp/li/111/321/7132123111.g_300-w-st_g.jpg",
        title: "Compact Travel Iron",
        des: "Perfect for business trips or quick fixes on the go.",
        price: "1299",
        fakePrice: "2499",
        discount: "48",
        rating: "4.3",
        ratingQuantity: "327",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/312/772/7102772312.g_300-w-st_g.jpg",
        title: "Magnetic Phone Stand",
        des: "Sleek and foldable design for desk and bedside use.",
        price: "899",
        fakePrice: "1599",
        discount: "44",
        rating: "4.1",
        ratingQuantity: "590",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/723/511/7123511723.g_300-w-st_g.jpg",
        title: "Waterproof Shower Speaker",
        des: "Enjoy your favorite tracks even in the shower.",
        price: "1599",
        fakePrice: "2999",
        discount: "47",
        rating: "4.5",
        ratingQuantity: "422",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/903/712/7142712903.g_300-w-st_g.jpg",
        title: "Laptop Cooling Pad",
        des: "Prevent overheating with this ultra-quiet cooling base.",
        price: "1799",
        fakePrice: "3499",
        discount: "49",
        rating: "4.0",
        ratingQuantity: "518",
      },
    ],
  },
  qList: {
    type: "qList",
    mainTitle: "Tauhff",
    subTitle: "by Bharat",
    metaData: [
      {
        image:
          "https://gd.image-qoo10.jp/li/401/568/7125684401.g_300-w-st_g.jpg",
        title: "Elegant Silk Scarf",
        des: "Smooth texture with vibrant prints, perfect for any season.",
        price: "2499",
        fakePrice: "4999",
        discount: "50",
        rating: "4.7",
        ratingQuantity: "325",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/525/689/7156892525.g_300-w-st_g.jpg",
        title: "Leather Ankle Boots",
        des: "Comfortable fit with stylish design for urban wear.",
        price: "8999",
        fakePrice: "11999",
        discount: "25",
        rating: "4.3",
        ratingQuantity: "210",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/631/470/7134702631.g_300-w-st_g.jpg",
        title: "Classic Denim Jacket",
        des: "Timeless denim jacket with a tailored fit.",
        price: "5999",
        fakePrice: "7999",
        discount: "25",
        rating: "4.5",
        ratingQuantity: "478",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/789/302/7123023789.g_300-w-st_g.jpg",
        title: "Casual Cotton Tee",
        des: "Soft, breathable cotton t-shirt in multiple colors.",
        price: "1499",
        fakePrice: "2499",
        discount: "40",
        rating: "4.2",
        ratingQuantity: "580",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/804/111/7111111804.g_300-w-st_g.jpg",
        title: "Chic Sunglasses",
        des: "UV protection with a sleek modern frame design.",
        price: "3499",
        fakePrice: "6999",
        discount: "50",
        rating: "4.6",
        ratingQuantity: "132",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/912/256/7152562912.g_300-w-st_g.jpg",
        title: "Stylish Backpack",
        des: "Lightweight and durable, ideal for daily use.",
        price: "4599",
        fakePrice: "7999",
        discount: "43",
        rating: "4.4",
        ratingQuantity: "267",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/655/783/7167833655.g_300-w-st_g.jpg",
        title: "Elegant Wristwatch",
        des: "Minimalist design with leather strap and quartz movement.",
        price: "13999",
        fakePrice: "19999",
        discount: "30",
        rating: "4.8",
        ratingQuantity: "183",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/702/498/7144982702.g_300-w-st_g.jpg",
        title: "Comfort Fit Joggers",
        des: "Soft fabric and elastic waist, perfect for workouts.",
        price: "2299",
        fakePrice: "3999",
        discount: "42",
        rating: "4.1",
        ratingQuantity: "355",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/810/653/7136532810.g_300-w-st_g.jpg",
        title: "Floral Print Dress",
        des: "Lightweight fabric with a flattering A-line silhouette.",
        price: "4999",
        fakePrice: "8999",
        discount: "44",
        rating: "4.3",
        ratingQuantity: "290",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/921/784/7127843921.g_300-w-st_g.jpg",
        title: "Knitted Beanie Hat",
        des: "Warm and cozy, perfect for chilly days.",
        price: "1299",
        fakePrice: "1999",
        discount: "35",
        rating: "4.0",
        ratingQuantity: "150",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/834/569/7165692834.g_300-w-st_g.jpg",
        title: "Leather Belt",
        des: "Classic brown leather belt with metal buckle.",
        price: "1999",
        fakePrice: "3499",
        discount: "43",
        rating: "4.5",
        ratingQuantity: "202",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/945/312/7133122945.g_300-w-st_g.jpg",
        title: "Retro Sunglasses",
        des: "Round frame with tinted lenses for a vintage look.",
        price: "2999",
        fakePrice: "5499",
        discount: "45",
        rating: "4.4",
        ratingQuantity: "175",
      },
    ],
  },
  simpleHoriList: {
    type: "simpleHoriList",
    mainTitle: "Wweejke",
    metaData: [
      {
        image:
          "https://gd.image-qoo10.jp/li/421/796/7147960421.g_300-w-st_g.jpg",
        title: "Ruffled Sleeve Blouse",
        des: "Chic and breezy, perfect for everyday casual.",
        price: "1799",
        fakePrice: "3299",
        discount: "45",
        rating: "4.5",
        ratingQuantity: "384",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/350/964/7109640350.g_300-w-st_g.jpg",
        title: "A-Line Summer Dress",
        des: "Soft pastel tones with a light flare cut.",
        price: "2499",
        fakePrice: "4999",
        discount: "50",
        rating: "4.6",
        ratingQuantity: "412",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/808/063/7120638808.g_300-w-st_g.jpg",
        title: "High-Waist Wide Pants",
        des: "Comfort meets style with this flowy fit.",
        price: "1899",
        fakePrice: "3799",
        discount: "50",
        rating: "4.2",
        ratingQuantity: "219",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/312/685/7146850312.g_300-w-st_g.jpg",
        title: "Buttoned Midi Skirt",
        des: "A classic choice for modern office looks.",
        price: "2699",
        fakePrice: "3999",
        discount: "32",
        rating: "4.3",
        ratingQuantity: "198",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/905/253/7102535905.g_300-w-st_g.jpg",
        title: "Lace Trim Cami Top",
        des: "Delicate lace detailing for a romantic touch.",
        price: "1399",
        fakePrice: "2899",
        discount: "52",
        rating: "4.7",
        ratingQuantity: "345",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/739/847/7168474739.g_300-w-st_g.jpg",
        title: "Floral Wrap Dress",
        des: "Bright floral prints with a flattering silhouette.",
        price: "2999",
        fakePrice: "5999",
        discount: "50",
        rating: "4.5",
        ratingQuantity: "220",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/101/764/7137640101.g_300-w-st_g.jpg",
        title: "Knitted Crop Cardigan",
        des: "Layer up in style with this soft knit.",
        price: "1999",
        fakePrice: "3499",
        discount: "43",
        rating: "4.6",
        ratingQuantity: "298",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/712/541/7125410712.g_300-w-st_g.jpg",
        title: "Pleated Mini Skirt",
        des: "Youthful charm with preppy vibes.",
        price: "1599",
        fakePrice: "2899",
        discount: "45",
        rating: "4.4",
        ratingQuantity: "189",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/634/289/7152890634.g_300-w-st_g.jpg",
        title: "Off-Shoulder Top",
        des: "Effortlessly flirty with an elastic neckline.",
        price: "1799",
        fakePrice: "3599",
        discount: "50",
        rating: "4.3",
        ratingQuantity: "174",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/545/061/7160610545.g_300-w-st_g.jpg",
        title: "Boho Maxi Dress",
        des: "Flowy style with subtle prints and waist tie.",
        price: "3599",
        fakePrice: "6299",
        discount: "43",
        rating: "4.5",
        ratingQuantity: "201",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/723/848/7138480723.g_300-w-st_g.jpg",
        title: "Frill Hem Tunic",
        des: "Loose fit tunic with cute frilly accents.",
        price: "1699",
        fakePrice: "3099",
        discount: "45",
        rating: "4.2",
        ratingQuantity: "146",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/841/722/7167220841.g_300-w-st_g.jpg",
        title: "Casual Hoodie Dress",
        des: "Cozy hoodie with dressy flair for off-duty days.",
        price: "2799",
        fakePrice: "4999",
        discount: "44",
        rating: "4.6",
        ratingQuantity: "332",
      },
    ],
  },

  indeList: {
    type: "indeList",
    mainTitle: "RRfwewej",
    metaData: [
      {
        image:
          "https://gd.image-qoo10.jp/li/103/780/7137800103.g_300-w-st_g.jpg",
        title: "Vintage Floral Skirt",
        des: "Classic blooms with a modern high-waist cut.",
        price: "1890",
        fakePrice: "3290",
        discount: "42",
        rating: "4.6",
        ratingQuantity: "354",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/273/936/7159367273.g_300-w-st_g.jpg",
        title: "Casual Knit Pullover",
        des: "Perfect for chilly days with a relaxed fit.",
        price: "2290",
        fakePrice: "3990",
        discount: "43",
        rating: "4.4",
        ratingQuantity: "285",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/330/980/7169800330.g_300-w-st_g.jpg",
        title: "Puff Sleeve Top",
        des: "Statement sleeves with a cropped look.",
        price: "1599",
        fakePrice: "2899",
        discount: "45",
        rating: "4.5",
        ratingQuantity: "193",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/120/968/7159689120.g_300-w-st_g.jpg",
        title: "Linen Blend Trousers",
        des: "Effortless summer look with breathable comfort.",
        price: "2790",
        fakePrice: "4890",
        discount: "43",
        rating: "4.2",
        ratingQuantity: "174",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/145/310/7163104145.g_300-w-st_g.jpg",
        title: "Flared Denim Skirt",
        des: "Retro-inspired with stretch comfort.",
        price: "1990",
        fakePrice: "3590",
        discount: "44",
        rating: "4.7",
        ratingQuantity: "298",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/813/858/7108580813.g_300-w-st_g.jpg",
        title: "Striped Shirt Dress",
        des: "Laid-back stripes in a relaxed silhouette.",
        price: "3099",
        fakePrice: "5599",
        discount: "45",
        rating: "4.5",
        ratingQuantity: "211",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/708/848/7148480708.g_300-w-st_g.jpg",
        title: "Soft Cotton Tunic",
        des: "Breathable fabric with a flattering flow.",
        price: "1790",
        fakePrice: "3190",
        discount: "44",
        rating: "4.3",
        ratingQuantity: "167",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/502/794/7167947502.g_300-w-st_g.jpg",
        title: "Ribbed Knit Set",
        des: "Trendy two-piece perfect for chill or run.",
        price: "3390",
        fakePrice: "5990",
        discount: "43",
        rating: "4.6",
        ratingQuantity: "204",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/251/170/7161701251.g_300-w-st_g.jpg",
        title: "Pleated Check Skirt",
        des: "Classic preppy vibes with soft pleats.",
        price: "1490",
        fakePrice: "2790",
        discount: "47",
        rating: "4.4",
        ratingQuantity: "129",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/627/916/7139162627.g_300-w-st_g.jpg",
        title: "Flowy Layered Blouse",
        des: "Dressy and elegant, ideal for evenings.",
        price: "1999",
        fakePrice: "3799",
        discount: "47",
        rating: "4.5",
        ratingQuantity: "158",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/706/711/7137110706.g_300-w-st_g.jpg",
        title: "Relaxed Denim Overalls",
        des: "Youthful charm meets comfy layering.",
        price: "2999",
        fakePrice: "5199",
        discount: "42",
        rating: "4.6",
        ratingQuantity: "244",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/850/728/7137280850.g_300-w-st_g.jpg",
        title: "Basic Round Neck Tee",
        des: "Everyday comfort with a slim cut.",
        price: "990",
        fakePrice: "1990",
        discount: "50",
        rating: "4.3",
        ratingQuantity: "315",
      },
    ],
  },
};

export const categoryData = {
  Tops: {
    headerImage:
      "https://dp.image-qoo10.jp/dp2016/JP/GMKT.IMG/mall/2025/05/27/978e2418-2fb4-4427-9a4a-d3954233ed66.jpg",
    metaDataList: [
      {
        image:
          "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
        title: "Floral Print Maxi Dress",
        des: "Elegant floral print maxi dress with adjustable straps.",
        price: "2599",
        fakePrice: "3999",
        categoryId: "dresses",
        discount: "35",
        rating: "4.7",
        ratingQuantity: "1150",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
        title: "Basic White Cotton T-Shirt",
        des: "Comfortable cotton t-shirt with a classic fit.",
        price: "499",
        fakePrice: "699",
        categoryId: "tops",
        discount: "28",
        rating: "4.3",
        ratingQuantity: "900",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
        title: "High-Waist Skinny Jeans",
        des: "Stretchable denim skinny jeans with a high waist fit.",
        price: "1799",
        fakePrice: "2599",
        categoryId: "jeans",
        discount: "31",
        rating: "4.6",
        ratingQuantity: "1300",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
        title: "Striped Casual Shirt",
        des: "Lightweight striped shirt perfect for casual outings.",
        price: "1199",
        fakePrice: "1599",
        categoryId: "tops",
        discount: "25",
        rating: "4.4",
        ratingQuantity: "850",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
        title: "Pleated Midi Skirt",
        des: "Flowy pleated midi skirt with elastic waistband.",
        price: "1399",
        fakePrice: "1999",
        categoryId: "skirts",
        discount: "30",
        rating: "4.5",
        ratingQuantity: "700",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
        title: "Off-Shoulder Summer Top",
        des: "Light off-shoulder top made from breathable fabric.",
        price: "899",
        fakePrice: "1299",
        categoryId: "tops",
        discount: "31",
        rating: "4.2",
        ratingQuantity: "670",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
        title: "Classic Denim Jacket",
        des: "Stylish denim jacket with button-down front.",
        price: "2999",
        fakePrice: "3999",
        categoryId: "jackets",
        discount: "25",
        rating: "4.7",
        ratingQuantity: "1200",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
        title: "Wide-Leg Palazzo Pants",
        des: "Comfortable palazzo pants with high waist design.",
        price: "1599",
        fakePrice: "2299",
        categoryId: "bottoms",
        discount: "30",
        rating: "4.5",
        ratingQuantity: "730",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
        title: "Basic V-Neck Sweater",
        des: "Soft knit sweater with V-neck cut for casual wear.",
        price: "1499",
        fakePrice: "2199",
        categoryId: "tops",
        discount: "32",
        rating: "4.6",
        ratingQuantity: "880",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
        title: "Printed Wrap Dress",
        des: "Stylish wrap dress with floral print and waist tie.",
        price: "2499",
        fakePrice: "3499",
        categoryId: "dresses",
        discount: "29",
        rating: "4.8",
        ratingQuantity: "1050",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
        title: "Ribbed Tank Top",
        des: "Stretchy ribbed tank top for layering or standalone wear.",
        price: "599",
        fakePrice: "899",
        categoryId: "tops",
        discount: "33",
        rating: "4.4",
        ratingQuantity: "650",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
        title: "Wide-Leg Linen Pants",
        des: "Breathable linen pants with wide-leg cut for summer.",
        price: "1899",
        fakePrice: "2699",
        categoryId: "bottoms",
        discount: "29",
        rating: "4.5",
        ratingQuantity: "790",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
        title: "Cropped Hoodie Sweatshirt",
        des: "Cozy cropped hoodie with adjustable drawstrings.",
        price: "1599",
        fakePrice: "2299",
        categoryId: "tops",
        discount: "30",
        rating: "4.3",
        ratingQuantity: "980",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
        title: "Slim Fit Chinos",
        des: "Classic slim fit chinos suitable for casual or office wear.",
        price: "1699",
        fakePrice: "2499",
        categoryId: "bottoms",
        discount: "32",
        rating: "4.6",
        ratingQuantity: "890",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
        title: "Embroidered Kurti Top",
        des: "Elegant embroidered kurti with three-quarter sleeves.",
        price: "1799",
        fakePrice: "2599",
        categoryId: "tops",
        discount: "31",
        rating: "4.7",
        ratingQuantity: "700",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
        title: "Ruffled Sleeve Blouse",
        des: "Chic blouse with ruffled sleeves and button-down front.",
        price: "1299",
        fakePrice: "1899",
        categoryId: "tops",
        discount: "32",
        rating: "4.5",
        ratingQuantity: "840",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
        title: "Denim Shorts",
        des: "Casual denim shorts with frayed hems.",
        price: "999",
        fakePrice: "1499",
        categoryId: "bottoms",
        discount: "33",
        rating: "4.3",
        ratingQuantity: "920",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
        title: "Sleeveless Shirt Dress",
        des: "Lightweight shirt dress with sleeveless design for summers.",
        price: "1999",
        fakePrice: "2799",
        categoryId: "dresses",
        discount: "29",
        rating: "4.6",
        ratingQuantity: "730",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
        title: "Knit Cardigan Sweater",
        des: "Soft knit cardigan with button closure, perfect for layering.",
        price: "1799",
        fakePrice: "2599",
        categoryId: "jackets",
        discount: "31",
        rating: "4.7",
        ratingQuantity: "870",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
        title: "Paperbag Waist Trousers",
        des: "Stylish paperbag waist trousers with belt tie.",
        price: "1899",
        fakePrice: "2699",
        categoryId: "bottoms",
        discount: "30",
        rating: "4.5",
        ratingQuantity: "760",
      },
      {
        image:
          "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
        title: "Printed Boho Top",
        des: "Bohemian style printed top with flowy sleeves.",
        price: "999",
        fakePrice: "1499",
        categoryId: "tops",
        discount: "33",
        rating: "4.4",
        ratingQuantity: "660",
      },
    ],
  },
};

export const productData = {
  title: "Fwefji",
  des: "oewjfw wdfuhuweif we9fhuweuifh weuhfwehf wefhwe fwuehwwchwddiwdw dcwduic",
  price: "4735",
  fakePrice: "999999",
  discount: "40",
  rating: "4.4",
  ratingQuantity: "1324",
  images: [
    "https://gd.image-qoo10.jp/li/151/738/7159738151.g_400-w_g.jpg",
    "https://gd.image-qoo10.jp/ai/873/551/7159551873_00.g_400-w-st_g.jpg",
    "https://gd.image-qoo10.jp/ai/873/551/7159551873_01.g_400-w-st_g.jpg",
    "https://gd.image-qoo10.jp/ai/873/551/7159551873_02.g_400-w-st_g.jpg",
  ],
  detailImages: [
    "https://gd.image-qoo10.jp/li/151/738/7159738151.g_400-w_g.jpg",
    "https://gd.image-qoo10.jp/ai/873/551/7159551873_00.g_400-w-st_g.jpg",
    "https://gd.image-qoo10.jp/ai/873/551/7159551873_01.g_400-w-st_g.jpg",
    "https://gd.image-qoo10.jp/ai/873/551/7159551873_02.g_400-w-st_g.jpg",
  ],
};

export const SecondFlatListCategoryList = {
  categoryList: [
    "all",
    "dresses",
    "tops",
    "jeans",
    "skirts",
    "jackets",
    "bottoms",
  ],

  metaData: [
    {
      image: "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
      title: "Floral Print Maxi Dress",
      des: "Elegant floral print maxi dress with adjustable straps.",
      price: "2599",
      fakePrice: "3999",
      categoryId: "dresses",
      discount: "35",
      rating: "4.7",
      ratingQuantity: "1150",
    },
    {
      image: "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
      title: "Basic White Cotton T-Shirt",
      des: "Comfortable cotton t-shirt with a classic fit.",
      price: "499",
      fakePrice: "699",
      categoryId: "tops",
      discount: "28",
      rating: "4.3",
      ratingQuantity: "900",
    },
    {
      image: "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
      title: "High-Waist Skinny Jeans",
      des: "Stretchable denim skinny jeans with a high waist fit.",
      price: "1799",
      fakePrice: "2599",
      categoryId: "jeans",
      discount: "31",
      rating: "4.6",
      ratingQuantity: "1300",
    },
    {
      image: "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
      title: "Striped Casual Shirt",
      des: "Lightweight striped shirt perfect for casual outings.",
      price: "1199",
      fakePrice: "1599",
      categoryId: "tops",
      discount: "25",
      rating: "4.4",
      ratingQuantity: "850",
    },
    {
      image: "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
      title: "Pleated Midi Skirt",
      des: "Flowy pleated midi skirt with elastic waistband.",
      price: "1399",
      fakePrice: "1999",
      categoryId: "skirts",
      discount: "30",
      rating: "4.5",
      ratingQuantity: "700",
    },
    {
      image: "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
      title: "Off-Shoulder Summer Top",
      des: "Light off-shoulder top made from breathable fabric.",
      price: "899",
      fakePrice: "1299",
      categoryId: "tops",
      discount: "31",
      rating: "4.2",
      ratingQuantity: "670",
    },
    {
      image: "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
      title: "Classic Denim Jacket",
      des: "Stylish denim jacket with button-down front.",
      price: "2999",
      fakePrice: "3999",
      categoryId: "jackets",
      discount: "25",
      rating: "4.7",
      ratingQuantity: "1200",
    },
    {
      image: "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
      title: "Wide-Leg Palazzo Pants",
      des: "Comfortable palazzo pants with high waist design.",
      price: "1599",
      fakePrice: "2299",
      categoryId: "bottoms",
      discount: "30",
      rating: "4.5",
      ratingQuantity: "730",
    },
    {
      image: "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
      title: "Basic V-Neck Sweater",
      des: "Soft knit sweater with V-neck cut for casual wear.",
      price: "1499",
      fakePrice: "2199",
      categoryId: "tops",
      discount: "32",
      rating: "4.6",
      ratingQuantity: "880",
    },
    {
      image: "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
      title: "Printed Wrap Dress",
      des: "Stylish wrap dress with floral print and waist tie.",
      price: "2499",
      fakePrice: "3499",
      categoryId: "dresses",
      discount: "29",
      rating: "4.8",
      ratingQuantity: "1050",
    },
    {
      image: "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
      title: "Ribbed Tank Top",
      des: "Stretchy ribbed tank top for layering or standalone wear.",
      price: "599",
      fakePrice: "899",
      categoryId: "tops",
      discount: "33",
      rating: "4.4",
      ratingQuantity: "650",
    },
    {
      image: "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
      title: "Wide-Leg Linen Pants",
      des: "Breathable linen pants with wide-leg cut for summer.",
      price: "1899",
      fakePrice: "2699",
      categoryId: "bottoms",
      discount: "29",
      rating: "4.5",
      ratingQuantity: "790",
    },
    {
      image: "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
      title: "Cropped Hoodie Sweatshirt",
      des: "Cozy cropped hoodie with adjustable drawstrings.",
      price: "1599",
      fakePrice: "2299",
      categoryId: "tops",
      discount: "30",
      rating: "4.3",
      ratingQuantity: "980",
    },
    {
      image: "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
      title: "Slim Fit Chinos",
      des: "Classic slim fit chinos suitable for casual or office wear.",
      price: "1699",
      fakePrice: "2499",
      categoryId: "bottoms",
      discount: "32",
      rating: "4.6",
      ratingQuantity: "890",
    },
    {
      image: "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
      title: "Embroidered Kurti Top",
      des: "Elegant embroidered kurti with three-quarter sleeves.",
      price: "1799",
      fakePrice: "2599",
      categoryId: "tops",
      discount: "31",
      rating: "4.7",
      ratingQuantity: "700",
    },
    {
      image: "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
      title: "Ruffled Sleeve Blouse",
      des: "Chic blouse with ruffled sleeves and button-down front.",
      price: "1299",
      fakePrice: "1899",
      categoryId: "tops",
      discount: "32",
      rating: "4.5",
      ratingQuantity: "840",
    },
    {
      image: "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
      title: "Denim Shorts",
      des: "Casual denim shorts with frayed hems.",
      price: "999",
      fakePrice: "1499",
      categoryId: "bottoms",
      discount: "33",
      rating: "4.3",
      ratingQuantity: "920",
    },
    {
      image: "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
      title: "Sleeveless Shirt Dress",
      des: "Lightweight shirt dress with sleeveless design for summers.",
      price: "1999",
      fakePrice: "2799",
      categoryId: "dresses",
      discount: "29",
      rating: "4.6",
      ratingQuantity: "730",
    },
    {
      image: "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
      title: "Knit Cardigan Sweater",
      des: "Soft knit cardigan with button closure, perfect for layering.",
      price: "1799",
      fakePrice: "2599",
      categoryId: "jackets",
      discount: "31",
      rating: "4.7",
      ratingQuantity: "870",
    },
    {
      image: "https://gd.image-qoo10.jp/li/107/583/6920583107.g_300-w-st_g.jpg",
      title: "Paperbag Waist Trousers",
      des: "Stylish paperbag waist trousers with belt tie.",
      price: "1899",
      fakePrice: "2699",
      categoryId: "bottoms",
      discount: "30",
      rating: "4.5",
      ratingQuantity: "760",
    },
    {
      image: "https://gd.image-qoo10.jp/li/312/752/7128752312.g_300-w-st_g.jpg",
      title: "Printed Boho Top",
      des: "Bohemian style printed top with flowy sleeves.",
      price: "999",
      fakePrice: "1499",
      categoryId: "tops",
      discount: "33",
      rating: "4.4",
      ratingQuantity: "660",
    },
  ],
};

export const naviggations = {
  Cloths: require("./assets/images/cloths.png"),
  Perfuems: require("./assets/images/perfuems.png"),
  Flowers: require("./assets/images/flowers.png"),
  MakeUp: require("./assets/images/makeup.png"),
  Haircare: require("./assets/images/haircare.png"),
  Skincare: require("./assets/images/skincare.png"),
  Bags: require("./assets/images/bags.png"),
  Spa: require("./assets/images/spa.png"),
  Glasses: require("./assets/images/glasses.png"),
  Rings: require("./assets/images/rings.png"),
  Accessries: require("./assets/images/accessries.png"),
  Sandels: require("./assets/images/sandels.png"),
  Watches: require("./assets/images/watches.png"),
  Footwear: require("./assets/images/boots.png"),
};
